config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  namespace :account do
    resources :offers, only: [:index]
    resources :bookings, only: [:index]
  end

  resources :offers do
    resources :bookings, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer, class_name: 'User'
  belongs_to :offer

  validates :start_date, :end_date, presence: true
  validate :check_overlapping

  def check_overlapping
    overlap = Booking.where('offer_id = ? AND start_date <= ? AND end_date >= ?', offer_id, end_date, start_date)

    if overlap.exists?
      period = overlap.pluck(:start_date, :end_date)
      booked_period = period.map {|x| x.join(' => ')}.join(', ')
      errors.add(:base, "This slot is not available. It has been booked on these dates: #{booked_period}")
    end
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :offers, foreign_key: 'owner_id', dependent: :destroy

  has_many :bookings, foreign_key: 'customer_id', dependent: :destroy
end

app/controllers/account/bookings_controller.rb
module Account
  class BookingsController < ApplicationController
    before_action :authenticate_user!

    def index
      @bookings = current_user.bookings.includes(:offer)
    end
  end
end

app/controllers/account/offers_controller.rb
module Account
  class OffersController < ApplicationController
    before_action :authenticate_user!

    def index
      @offers = current_user.offers
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def create
    @booking = current_user.bookings.new(booking_params)
    if @booking.save
      redirect_to account_bookings_path, notice: "Your booking is successful"
    else
      redirect_to offer_path(@booking.offer), alert: @booking.errors.full_messages.join("\n")
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :offer_id)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def show
    @offer = Offer.find_by_id(params[:id])
    @booking = @offer.bookings.build
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @offers = Offer.includes(:owner)
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container mt-3">
  <h3>Offer for <%= @offer.name %></h3>
  <% count = @offer.bookings.count %>
  <% if count > 0 %>
    <p class="text-danger">This has been booked <%= @offer.bookings.count %> times</p>
  <% end %>
  <%= simple_form_for @booking do |f| %>
    <%= f.input :start_date, as: :date %>
    <%= f.input :end_date, as: :date %>
    <%= f.input :offer_id, as: :hidden, input_html: { value: @offer.id } %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/offers/show.html.erb
<div class="container mt-3">
  <h3><%= @offer.name %></h3>
  <p><%= @offer.description %></p>
  <% count = @offer.bookings.count %>
  <% if count > 0 %>
    <p class="text-danger">This has been booked <%= @offer.bookings.count %> times</p>
  <% end %>
  <h3>Make a reservation</h3>
  <%= simple_form_for [@offer, @booking] do |f| %>
    <%= f.input :start_date, as: :date %>
    <%= f.input :end_date, as: :date %>
    <%= f.input :remarks %>
    <%= f.input :offer_id, as: :hidden, input_html: { value: @offer.id } %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="container text-center mt-5">
  <h2>Book a flat</h2>
  <p>Check out the offers below</p>

  <div class="mt-3 d-flex">
    <% @offers.each do |offer| %>
      <div class="offer">
        <b><%= offer.name %></b> <br>
        <%= offer.description %> <br>
        Listed by <%= offer.owner.name %> <br>
        Price: $<%= offer.price %>
        <%= link_to "Book", offer_path(offer), class: "btn btn-primary btn-block mt-3" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Dashboard", account_offers_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>